travis:
  secure:
    BINSTAR_TOKEN: bGf1kpUhc0FoTs8appABLT2uZMlbaULc50j2w3YExjP+I4vYX3bLGWLVrhlNWQ432aZZq2xenSOCLUNJBUPYPoWkDgbmMvDSu82/g9imuSw0q0qd02AY7aMIIBGEUnpFvULmxnMeJ9EJ3gndrWs/kTWiKr+fGyP+EhDxo0PESvjdDN33ar8zLnXunX6d9/RiZsM/sbsCspvR0cBn/GPKWpwO7qttPjo7286yinLSJVRZxBsSjKwCzjmGsYrrSNmeZLGuML8N/tRIHBIqCpWxlFbkOdGXogdIsNbwfJ44mLb2xh1a0VrtVDoI9Q7TkFfoT444vXDsiKud2E2XkbqKlmFX1+dQA+6c684VYzlVbNgTb9xCPmkNpYMzMi8QJqb9zJ5lYJhlZRmHkFMYPi8pXpiAU8Bxkoa+jQ31uhoH0s96rrTDD4bSlimibPJ8hUIhh87CfVwUMrO7ih85aEbHgKfEEFWSCGqUpfhmgk0IyRDZBxZMvegsr2Bg/KhCFG/Y42aODEjMf027VilDT+ZUAFU6bzikE4aoPd6nz2RW75ZiurMvYjvGGHvDswQoQ8wd17ajPyInp2omsbg47jiwIN2hjhAUWKMoSbBtP0qb6B6Aviq8BWPGzEzJNTO1U5l1voGlrt+4Dvkrx4JIbsi3Ig/LRxVjNDxdxhka1wq4z8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
